### ISSUE TITLE
按照文档配置的  出现这个错误  你有遇到吗？

### ISSUE THREAD

**Issue by Moshimol** [Dx-zuo/amap_map_fluttify#1]
Error Domain=AMapFoundationErrorPrivacyShowUnknow Code=555570 "(null)" UserInfo={info=使用MAMapKit3D SDK 功能前请设置隐私权政策是否弹窗告知用户}
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(viewId无对应对象, viewId无对应对象, viewId无对应对象, null)

**Comment by Dx-zuo** [comment]
使用MAMapKit3D SDK 功能前请设置隐私权政策是否弹窗告知用户, 没有设置授权

**Comment by Moshimol** [comment]
MAMapKit3D SDK 这个是没有的用到的  
  await AmapSearch.instance.updatePrivacyShow(true);
  await AmapSearch.instance.updatePrivacyAgree(true);
  只有这两个
